### ISSUE TITLE
Arbitrary Exp

### ISSUE THREAD

**Issue by Wizek** [RyanGlScott/text-show-instances#1]
Hello!

Do I see it correctly that in [this file](http://hackage.haskell.org/package/text-show-instances-0.4/src/tests/Instances/Language/Haskell/TH.hs) you are defining an Arbitrary instance for Haskell AST? Could that be used to get arbitrary haskell source strings via QuickCheck? And if so perhaps would you be willing to move that portion out to a separate cabal package so that others, including myself could use it?

**Comment by RyanGlScott** [comment]
To be honest, that's some of the laziest Haskell code I've ever written. My goal when defining those `Arbitrary` instances was not to have robust generation of Haskell source strings, but to produce simple expressions that I could use to test `TextShow` instances. 

The commented-out code was my original attempt, but due to the high levels of mutual recursion among Template Haskell data types, they were too slow for practical use. To get around this, I use [trivial values](https://github.com/RyanGlScott/text-show-instances/blob/5db3b09a3ee04e10f7ee79b22221aef07bf3304b/tests/Instances/Language/Haskell/TH.hs#L544) for most types, which means any Haskell expressions generated by this code would be extremely uninteresting.

**Comment by Wizek** [comment]
You mean the slowness came due to the recursion going too deep and generating too long of an AST? If so couldn't that be solved by allowing to specify the desired depth and/or length of the arbitrary expression?

_A bit of context: I am thinking of using automatically generated expressions to test the correctness of [this parser](https://github.com/Wizek/dump/blob/24294baef18a99643117b15e5ce3636126bafdba/src/Internal/Parser.hs#L5)._

**Comment by RyanGlScott** [comment]
> If so couldn't that be solved by allowing to specify the desired depth and/or length of the arbitrary expression?

Probably. I'm not an experienced `QuickCheck` user—I just needed a quick test for `text-show-instances`, and that was what I cobbled together. If you want to extend it, you're more than welcome to use that code as a start, but I don't really have the time to mess with it.

**Comment by RyanGlScott** [comment]
I'm going to close this, since it seems only tangentially related to `text-show-instances`.
